### PR TITLE
change IRkernel repo and install IRkernel using devtools

### PR DESCRIPTION
**Pull request by lisamurie**
This is the only way I was able to install IRKernel.

### CODE REVIEW

**Comment by hermantolentino** [comment]
Thanks Lisa, I did not anticipate that the irkernel site would fail. I will try to test the patch soon.

**Comment by lisamurie** [comment]
Please do test. I was finally able to successfully run jupyterhub after
this change.

**Comment by hermantolentino** [comment]
I applied the same change to Dockerfile-packages

**Comment by lisamurie** [comment]
Great.

On Sun, Aug 14, 2016 at 11:11 PM, Herman Tolentino <notifications@github.com

**Comment by hermantolentino** [comment]
It's working on my external VM. https://epispider.io:8000 
Good job!

Get Outlook for iOS

On Mon, Aug 15, 2016 at 12:11 AM -0400, "lisamurie" notifications@github.com wrote:

Great.

On Sun, Aug 14, 2016 at 11:11 PM, Herman Tolentino <notifications@github.com

**Comment by lisamurie** [comment]
Awesome :)

**Comment by hermantolentino** [comment]
Hi Lisa, I have one new commit to make (docker-jupyterhub), streamlined Dockerfiles (installed as dependencies) plus one for deep learning (tensorflow, theano and keras).

**Pull request merged**
